version: '3.9'

services:
  jira-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    ports:
      - "5434:5432"
    volumes:
      - jira-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jira -d jira" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jira-db-test:
    image: postgres:15-alpine
    container_name: postgres-db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira-test
    ports:
      - "5433:5432"
    volumes:
      - jira-db-test-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jira -d jira-test" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jira-db-data:
  jira-db-test-data: